apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-api
  template:
    metadata:
      labels:
        app: redis-api
    spec:
      containers:
      - name: redis-api
        image: sajid138/redis-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: SPRING_REDIS_HOST
        - name: SPRING_REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: SPRING_REDIS_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: redis-api
spec:
  selector:
    app: redis-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080


